version: "3.0"

services:
  storage:
    image: 'redis'
    volumes:
      - ./data:/data
  counter:
    image: books
    working_dir: /app
    ports:
      - 8080:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run start
    depends_on:
      - storage





